### ISSUE TITLE
Is this repo still active?

### ISSUE THREAD

**Issue by pllim** [spacetelescope/stsci.numdisplay#3]
Do people use this?

**Comment by jhunkeler** [comment]
Aside from including it in stsci-hst nothing else is using it directly...
https://github.com/astroconda/astroconda-dev/search?utf8=%E2%9C%93&q=numdisplay

**Comment by SaOgaz** [comment]
Spoke with Warren, and it was decided that this repo is still 'active'.  But I will keep it on my list of possible re-organization of stuff. Closing call!
